name: Checkov
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Generate Checkov report & upload to Datadog
        run: |
          pip install -U checkov
          npm install -g @datadog/datadog-ci
          checkov -d . -o junitxml -s > results.xml
          DATADOG_API_KEY=${{ secrets.DATADOG_API_KEY }} datadog-ci junit upload --service ${GITHUB_REPOSITORY} results.xml
      - name: Test with Checkov
        id: checkov
        uses: bridgecrewio/checkov-action@master
        with:
          quiet: true
