name: IaC trace

on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  yor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout repo
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
      - name: Run yor action and commit
        uses: bridgecrewio/yor-action@main
        with:
          commit_changes: NO
      - name: Update resource tags
        uses: technote-space/create-pr-action@v2
        with:
          COMMIT_MESSAGE: 'Yor: update update resource tags'
          COMMIT_NAME: 'GitHub Actions: Yor'
          COMMIT_EMAIL: 'infra@smartpension.co.uk'
          PR_BRANCH_NAME: 'yor-tag-update-${PR_ID}'
          PR_TITLE: 'Yor: update resource tags'
